"""add the track_id column to the students table

Revision ID: 1670c4023fef
Revises: 1824aa25c564
Create Date: 2024-09-07 22:03:44.413309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1670c4023fef'
down_revision = '1824aa25c564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tracks', ['track_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('track_id')

    # ### end Alembic commands ###
