"""student table

Revision ID: 410707365512
Revises: c3e6b6d80146
Create Date: 2024-09-07 18:27:54.636153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410707365512'
down_revision = 'c3e6b6d80146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('age')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
